// permissions.js
export const ROLES = {
    ADMIN: "superAdmin",
    FINANCE_ADMIN: "finance_admin",
    STUDENT_ADMIN: "student_admin",
    PRM_ADMIN: "prm_admin",
    CONTENT_ADMIN: "content_admin",
};

export const PERMISSIONS = {
    [ROLES.ADMIN]: [
        "/dashboard",
        "/quiz",
        "/question",
        "/subject",
        "/course",
        "/chapter",
        "/bundle",
        "/batch",
        "/topic",
        "/video",
        "/section",
        "/reading",
        "/advertisement",
        "/flashcard",
        "/shop-payment",
        "/installment",
        "/shop-purchase",
        "/purchase-track",
        "/student",
        "/prm-dashboard",
        "/shop-product",
        "/shop-plan",
        "/category",
    ],

    [ROLES.CONTENT_ADMIN]: [
        "/course",
        "/dashboard",
        "/quiz",
        "/question",
        "/bundle",
        "/batch",
        "/video",
        "/section",
        "/reading",
        "/advertisement",
        "/flashcard",
    ],
    [ROLES.FINANCE_ADMIN]: ["/shop-payment", "/installment", "/shop-purchase"],
    [ROLES.STUDENT_ADMIN]: ["/purchase-track", "/student"],
    [ROLES.PRM_ADMIN]: ["/prm-dashboard"],
};
